-- Golf Charity Subscription Platform schema for Supabase

-- 1) profiles
create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  handicap integer,
  charity_id bigint,
  charity_pct integer not null default 10 check (charity_pct >= 10 and charity_pct <= 100),
  subscription_status text not null default 'inactive',
  created_at timestamptz not null default now()
);

-- 2) charities
create table charities (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  image_url text,
  featured boolean not null default false,
  created_at timestamptz not null default now()
);

-- Add FK from profiles.charity_id -> charities.id after both tables exist
alter table profiles
  add constraint profiles_charity_id_fkey
  foreign key (charity_id)
  references charities(id)
  on delete set null;

-- 3) scores
create table scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references profiles(id) on delete cascade,
  score integer not null check (score >= 1 and score <= 45),
  played_at date not null,
  created_at timestamptz not null default now()
);

-- 4) subscriptions
create table subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references profiles(id) on delete cascade,
  stripe_subscription_id text,
  stripe_customer_id text,
  plan text not null check (plan in ('monthly', 'yearly')),
  status text not null default 'inactive',
  current_period_end timestamptz,
  created_at timestamptz not null default now()
);

-- 5) draws
create table draws (
  id bigint generated by default as identity primary key,
  month date not null,
  numbers integer[] not null check (cardinality(numbers) = 5),
  status text not null default 'pending' check (status in ('pending', 'simulated', 'published')),
  draw_mode text not null default 'random' check (draw_mode in ('random', 'algorithmic')),
  jackpot_amount numeric(10,2) not null default 0,
  jackpot_carried_over boolean not null default false,
  created_at timestamptz not null default now()
);

-- 6) draw_results
create table draw_results (
  id bigint generated by default as identity primary key,
  draw_id bigint not null references draws(id) on delete cascade,
  user_id uuid not null references profiles(id) on delete cascade,
  match_type integer not null check (match_type in (3, 4, 5)),
  tier_pool_amount numeric(10,2) not null default 0,
  winners_count integer not null default 1,
  individual_share numeric(10,2) not null default 0,
  proof_url text,
  payment_status text not null default 'pending' check (payment_status in ('pending', 'approved', 'rejected', 'paid')),
  created_at timestamptz not null default now()
);

-- 7) donations
create table donations (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete set null,
  charity_id bigint not null references charities(id) on delete cascade,
  amount numeric(10,2) not null,
  stripe_payment_id text,
  created_at timestamptz not null default now()
);

-- Enable RLS on all tables
alter table profiles enable row level security;
alter table charities enable row level security;
alter table scores enable row level security;
alter table subscriptions enable row level security;
alter table draws enable row level security;
alter table draw_results enable row level security;
alter table donations enable row level security;

-- RLS policies: profiles
create policy "profiles_select_own"
  on profiles
  for select
  to authenticated
  using ((select auth.uid()) = id);

create policy "profiles_insert_own"
  on profiles
  for insert
  to authenticated
  with check ((select auth.uid()) = id);

create policy "profiles_update_own"
  on profiles
  for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

-- RLS policies: scores
create policy "scores_select_own"
  on scores
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "scores_insert_own"
  on scores
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "scores_update_own"
  on scores
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "scores_delete_own"
  on scores
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

-- RLS policies: charities
create policy "charities_select_all"
  on charities
  for select
  to anon, authenticated
  using (true);

-- RLS policies: subscriptions
create policy "subscriptions_select_own"
  on subscriptions
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

-- RLS policies: draws
create policy "draws_select_authenticated"
  on draws
  for select
  to authenticated
  using (true);

-- Fix draws RLS policy (drop wrong one, add correct one)
drop policy if exists "draws_select_authenticated" on draws;

create policy "draws_select_published"
  on draws
  for select
  to authenticated
  using (status = 'published');

-- RLS policies: draw_results
create policy "draw_results_select_own"
  on draw_results
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "draw_results_update_own"
  on draw_results
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- RLS policies: donations
create policy "donations_select_own"
  on donations
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "donations_insert_own"
  on donations
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

-- Trigger function: enforce max 5 scores per user
create or replace function limit_scores_per_user()
returns trigger
language plpgsql
as $$
begin
  if (select count(*) from scores where user_id = NEW.user_id) >= 5 then
    delete from scores
    where id = (
      select id from scores
      where user_id = NEW.user_id
      order by created_at asc
      limit 1
    );
  end if;
  return NEW;
end;
$$;

create trigger enforce_score_limit
  before insert on scores
  for each row
  execute function limit_scores_per_user();

-- Indexes
create index on scores(user_id);
create index on subscriptions(user_id);
create index on draw_results(draw_id);
create index on draw_results(user_id);
create index on donations(charity_id);

-- Seed: charities
insert into charities (name, description, image_url, featured) values
(
  'Golf for Good Foundation',
  'Providing underprivileged youth access to golf coaching, equipment and tournaments across the UK and Ireland.',
  'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=800',
  true
),
(
  'Green Hearts Cancer Trust',
  'Funding cutting-edge cancer research and patient support programmes through the power of sport and community.',
  'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800',
  false
),
(
  'Fairway Veterans Fund',
  'Supporting military veterans through therapeutic golf programmes, mental health resources and community events.',
  'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800',
  false
);
